language: c
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
script:
  - cmake . -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_FLAGS="-Werror -Wall -Wextra -pedantic"
  - make
  - make test
  - sudo make install
  - $CC version_compare/version_compare.c `pkg-config --libs --cflags libversion` -o test-installation
