language: c
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
    #before_install:
  #- sudo apt-get update -qq
    #  - sudo apt-get install -qq cmake cppcheck
script:
  - cmake . -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_FLAGS="-Werror -Wall -Wextra -pedantic"
  - make
  - make test
  - sudo make install
  - $CC `pkg-config --libs --cflags libversion` version_compare/version_compare.c -o test-installation
